version: '3.9'

services:
  pg:
    image: bitnami/postgresql:latest
    container_name: postgres
    restart: unless-stopped

    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
       - './docker:/docker-entrypoint-initdb.d'
    networks:
     - app_network
  app:
    build: .
    depends_on:
      - pg
    container_name: brev-ly-server
    restart: unless-stopped
    ports:
      - 3000:$PORT
    environment:
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
